services:
  filesystem-mcp:
    build:
      context: .
      dockerfile: dockerfile

    ports:
      - "8000:8000"

    environment:
      WORKSPACE_ROOT: /workspace
      LOG_LEVEL: INFO

    volumes:
      - /Users/priyanshu/Desktop/agenticWorkflow:/workspace